spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nba2k_backend?useSSL=false&serverTimezone=UTC
    username: root
    password: 102202
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
